### ISSUE TITLE
Combinator after clear cache freeze the server

### ISSUE THREAD

**Issue by psp589** [Lombiq/Combinator#12]
I have a multitenant configuration of orchard 1.9.3  and every time I clear combinator cache the server gets unresponsive for several minutes, at least 10, what could be the reason of it ? is there any way of avoiding it?

**Comment by Piedone** [comment]
Do you use local media storage? Because then this can be caused by IIS restarting the app (though 10 minutes seems excessive, does your app's start takes so much time?), see: https://github.com/OrchardCMS/Orchard/issues/4631

**Comment by Piedone** [comment]
Assuming it was the IIS restart. Please come back if you have updates.
