### ISSUE TITLE
Combinator fails in Redis setup

### ISSUE THREAD

**Issue by kumards** [Lombiq/Combinator#14]
CacheServiceMonitor class internally uses ConcurrentDictionary to track cachekeys. This ConcurrentDictionary does not reflect the previous entries added when the redis caching is enabled.
I guess, the modified ConcurrentDictionary must be persisted every time it goes through a change since the persistence is not automatic.

**Comment by Piedone** [comment]
So you mean that when the dictionary is changed, it should be explicitly Put() into the cache to persist it?

**Comment by kumards** [comment]
@Piedone thats right. 
I do not know if it is a good idea since it may lead to a racing condition between the nodes behind the loadbalancer, leading to one overwriting another nodes data.

Do you think Combinator should use ICacheManager service for caching at individual node level and using ISignal (distributed signals) to propagate the changes across the nodes?

**Comment by Piedone** [comment]
Hmm, good point. Actually the issue here is not with that Combinator uses the distributed cache, but rather that it uses CacheServiceMonitor from Helpful Libraries to interact with it. This could indeed solved by using ICacheManager (as it has this monitoring kind of API) or not using CacheServiceMonitor. I'll look into this.

**Comment by Piedone** [comment]
I changed caching to use ICacheManager, so you need to enable Distributed Signals. Could you please check the new code?

**Comment by kumards** [comment]
@Piedone I really appreciate for the quick fix. This fix resolved the issue with Redis!

I am yet to test this against multi node setup. I will keep you posted on this as I progress.

**Comment by Piedone** [comment]
Great, thanks. Please open a new issue if one is needed.
