### ISSUE TITLE
Invalid URI: The hostname could not be parsed exception

### ISSUE THREAD

**Issue by kumards** [Lombiq/Combinator#18]
I have noticed there are quite a few errors like below in the log file. 

```
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Orchard.DisplayManagement.Descriptors.ResourceBindingStrategy.StaticFileBindingStrategy.GetAlternateShapeNameFromFileName(String fileName) in D:\Proj\Src\Orchard\DisplayManagement\Descriptors\ResourceBindingStrategy\StylesheetBindingStrategy.cs:line 46
```

My observation was, the below line from method CombinedResourceManager.TraverseResouceShapes supplies a fullpath value(like //127.0.0.1:10000/devstoreaccount1/media/Default/_PiedoneModules/Combinator/Styles/-2140532205-6.css?timestamp=131261368560000000) that's already been combined by the combinator. 

`var shapeName = StaticFileBindingStrategy.GetAlternateShapeNameFromFileName(fullPath);
`

My combinator settings are not right?

**Comment by Piedone** [comment]
Could you please tell what version of Orchard and Combinator are you using? From the latter there was no release for a long time, so a commit reference would be needed.

**Comment by kumards** [comment]
Orchard 1.9 and Combinator 2.0

**Comment by kumards** [comment]
Zoltán, the below changeset fixed the problem. Apparently the fix is from you.

https://github.com/OrchardCMS/Orchard/commit/77f3a031c5837aa399d055431780e52650d7c1a0

**Comment by Piedone** [comment]
Nice :-).
