### ISSUE TITLE
Clear cache for a fresh deployment (COLI-1199)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/Combinator#21]
I'm looking for the simplest way to get the Combinator cache cleared when the application is deployed and then starts for the first time.

The best I came up with so far that is reliable and simple enough is that the deployment package includes a specific marker file that Combinator would detect when the tenant starts. If the file is present, Combinator clears its cache and then deletes the file so that subsequent shell starts wouldn't trigger the cache clear process.

For the deployment process to pick the file up automatically (without changing `Orchard.proj` and ideally `Piedone.Combinator.csproj` either) it should be in the `App_Data` folder, e.g. `/App_Data/Sites/<tenantname>/_PiedoneModules/Combinator/`, so that it can also be tenant-specific, but the file needs to be checked into the repository.

Keep in mind that the context here is a single-tenant application or one that has a low number of tenants, thus I didn't want to overengineer this for proper scalability unless it's actually needed.

**Comment by Piedone** [comment]
This looks like a good approach, yes, and I can't think of a simpler one. A different but more complex one would be for a CI process to call an API endpoint, or for Combinator to hash the files and clear the cache if they changed (though the latter would rather be needed on all app starts, not just the first one, but would only clear the cache when indeed needed).

**Comment by BenedekFarkas** [comment]
Sounds good, thanks!
